#!/usr/bin/env zsh


# dotfiles home
export DOTFILES_HOME="$HOME/repos/dotfiles"

# XDG directories
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:$XDG_DATA_DIRS"
export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# default editor
export EDITOR=/usr/bin/nvim

# GPG terminal stdin
export GPG_TTY=$(tty)

# apps
export ZINIT_HOME="$XDG_DATA_HOME/zinit/zinit.git"

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
[[ -d $CARGO_HOME ]] && . "$CARGO_HOME/env"

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export STARSHIP_CACHE="$XDG_CACHE_HOME/starship"
