format = '''
$sudo$directory $git_branch $git_status
$cmd_duration$character
'''

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
home_symbol = ' '
truncation_length = 5
truncate_to_repo = true
truncation_symbol = ' '
read_only = ' '
read_only_style = 'bold love'
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
repo_root_style = 'bg:overlay fg:pine'
repo_root_format = "[](fg:overlay)[ $repo_root]($repo_root_style)[ $path ]($style)[](fg:overlay) "

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[sudo]
disabled = false
symbol = ' '
style = 'bold'
format = '[$symbol]($style)'

[cmd_duration]
min_time = 60000
show_notifications = true
min_time_to_notify = 300000
style = 'bold gold'
format = '[$duration]($style) '

[character]
format = '$symbol '
success_symbol = '[](bold iris)'
error_symbol = '[](bold love)'
